# Generated by Django 2.1.5 on 2020-01-07 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoWe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=4, verbose_name='性别')),
                ('status', models.PositiveIntegerField(choices=[(0, '过期'), (1, '本期有效'), (2, '退出'), (3, '未激活')], default=3, verbose_name='用户状态')),
                ('s_weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='初始体重')),
                ('s_date', models.DateField(verbose_name='开始日期')),
                ('e_date', models.DateField(verbose_name='结束日期')),
                ('target', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='目标体重')),
                ('paid', models.IntegerField(verbose_name='押金')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': 'LoWe起始',
                'verbose_name_plural': 'LoWe起始',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '姓名',
            },
        ),
        migrations.CreateModel(
            name='StartLowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.PositiveIntegerField(verbose_name='期数')),
                ('payment', models.PositiveIntegerField(verbose_name='押金')),
                ('s_date', models.DateField(verbose_name='开始日期')),
                ('e_date', models.DateField(verbose_name='结束日期')),
                ('status', models.PositiveIntegerField(choices=[(0, '过期'), (1, '本期'), (2, '未激活')], default=2, verbose_name='状态')),
            ],
            options={
                'verbose_name': '减重期数',
                'verbose_name_plural': '减重期数',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='打卡日期')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='体重打卡')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.Name', verbose_name='姓名')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '体重打卡',
                'verbose_name_plural': '体重打卡',
                'get_latest_by': 'check_date',
            },
        ),
        migrations.AddField(
            model_name='lowe',
            name='batches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.StartLowe', verbose_name='期数'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.Name', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
