# Generated by Django 2.1.5 on 2020-01-07 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lowe', '0002_auto_20200107_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveIntegerField(verbose_name='押金')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.StartLowe', verbose_name='期数')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.Name', verbose_name='姓名')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '押金',
                'verbose_name_plural': '押金',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.PositiveIntegerField(verbose_name='押金')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.StartLowe', verbose_name='期数')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowe.Name', verbose_name='姓名')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '奖金',
                'verbose_name_plural': '奖金',
            },
        ),
    ]
