# Generated by Django 2.1.5 on 2020-01-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0003_deposit_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startlowe',
            name='payment',
        ),
    ]
