# Generated by Django 2.1.5 on 2020-02-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0004_remove_startlowe_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': '押金记录', 'verbose_name_plural': '押金记录'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': '参与者姓名', 'verbose_name_plural': '参与者姓名'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': '奖金分配', 'verbose_name_plural': '奖金分配'},
        ),
    ]
