# Generated by Django 2.1.5 on 2020-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0005_auto_20200201_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowe',
            options={'verbose_name': '每期减重开始时需要录入体重和目标', 'verbose_name_plural': '每期减重开始时需要录入体重和目标'},
        ),
        migrations.AlterModelOptions(
            name='startlowe',
            options={'verbose_name': '减重期数录入', 'verbose_name_plural': '减重期数录入'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'get_latest_by': 'check_date', 'verbose_name': '录入体重打卡', 'verbose_name_plural': '录入体重打卡'},
        ),
        migrations.AlterField(
            model_name='lowe',
            name='s_weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='初始体重'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='target',
            field=models.DecimalField(decimal_places=2, help_text='输入要减掉的公斤数，例如1.5', max_digits=4, verbose_name='减重目标'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='录入入体重到这里如82.5', max_digits=4, verbose_name='体重打卡'),
        ),
    ]
