# Generated by Django 2.1.5 on 2020-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0006_auto_20200201_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowe',
            name='paid',
        ),
        migrations.AddField(
            model_name='lowe',
            name='e_weight',
            field=models.DecimalField(decimal_places=2, help_text='不要手动填写', max_digits=4, null=True, verbose_name='本期结束体重'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='fund',
            field=models.IntegerField(help_text='不要手动填写', null=True, verbose_name='押金'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='rc_refund',
            field=models.DecimalField(decimal_places=2, help_text='不要手动填写', max_digits=5, null=True, verbose_name='北邮RC基金'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='refund',
            field=models.DecimalField(decimal_places=2, help_text='不要手动填写', max_digits=5, null=True, verbose_name='奖金'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='refund_weight',
            field=models.PositiveIntegerField(help_text='不要手动填写', null=True, verbose_name='奖金权重'),
        ),
        migrations.AddField(
            model_name='lowe',
            name='result',
            field=models.PositiveIntegerField(choices=[(0, '未完成'), (1, '完成'), (2, '完成>0.5kg'), (3, '完成>1kg')], help_text='不要手动填写', null=True, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '已结束'), (1, '本期有效'), (2, '退出'), (3, '未激活')], default=3, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='startlowe',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '已结束'), (1, '本期'), (2, '未激活')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='录入入体重到这里如82.5', max_digits=4, verbose_name='体重打卡'),
        ),
    ]
