# Generated by Django 2.1.5 on 2020-02-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0007_auto_20200202_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='name',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
