# Generated by Django 2.1.5 on 2020-02-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0008_auto_20200202_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startlowe',
            old_name='batch',
            new_name='batches',
        ),
    ]
