# Generated by Django 2.1.5 on 2020-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0009_auto_20200202_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowe',
            name='e_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='不要手动填写', max_digits=4, null=True, verbose_name='本期结束体重'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='fund',
            field=models.IntegerField(blank=True, help_text='不要手动填写', null=True, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='rc_refund',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='不要手动填写', max_digits=5, null=True, verbose_name='北邮RC基金'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='不要手动填写', max_digits=5, null=True, verbose_name='奖金'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='refund_weight',
            field=models.PositiveIntegerField(blank=True, help_text='不要手动填写', null=True, verbose_name='奖金权重'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '未完成'), (1, '完成'), (2, '完成>0.5kg'), (3, '完成>1kg')], help_text='不要手动填写', null=True, verbose_name='完成状态'),
        ),
    ]
