# Generated by Django 2.1.5 on 2020-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowe', '0010_auto_20200202_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowe',
            name='e_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='不要手动填写', max_digits=4, null=True, verbose_name='本期结束体重kg'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='rc_refund',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='不要手动填写', max_digits=5, null=True, verbose_name='RC基金'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='s_weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='初始体重kg'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='lowe',
            name='target',
            field=models.DecimalField(decimal_places=2, help_text='输入要减掉的公斤数，例如1.5', max_digits=4, verbose_name='减重目标kg'),
        ),
    ]
